### PR TITLE
fix: compile with poppler >= 22.01

### LINKED ISSUE #571: Compilation fails with error in pdf/XPDFRenderer.cpp
Version 1.6.1-5 fails to compile on Arch linux with the following error:

```src/pdf/XPDFRenderer.cpp: In constructor ‘XPDFRenderer::XPDFRenderer(const QString&, bool)’:
src/pdf/XPDFRenderer.cpp:99:74: error: no matching function for call to ‘PDFDoc::PDFDoc(GooString*, int, int, int)’
   99 |     mDocument = new PDFDoc(new GooString(filename.toLocal8Bit()), 0, 0, 0); // the filename GString is deleted on PDFDoc desctruction
      |                                                                          ^
In file included from src/pdf/XPDFRenderer.h:51,
                 from src/pdf/XPDFRenderer.cpp:30:
/usr/include/poppler/PDFDoc.h:371:5: note: candidate: ‘PDFDoc::PDFDoc()’
  371 |     PDFDoc();
      |     ^~~~~~
/usr/include/poppler/PDFDoc.h:371:5: note:   candidate expects 0 arguments, 4 provided
/usr/include/poppler/PDFDoc.h:139:14: note: candidate: ‘PDFDoc::PDFDoc(BaseStream*, const std::optional<GooString>&, const std::optional<GooString>&, void*, const std::function<void()>&)’
  139 |     explicit PDFDoc(BaseStream *strA, const std::optional<GooString> &ownerPassword = {}, const std::optional<GooString> &userPassword = {}, void *guiDataA = nullptr, const std::function<void()> &xrefReconstructedCallback = {});
      |              ^~~~~~
/usr/include/poppler/PDFDoc.h:139:33: note:   no known conversion for argument 1 from ‘GooString*’ to ‘BaseStream*’
  139 |     explicit PDFDoc(BaseStream *strA, const std::optional<GooString> &ownerPassword = {}, const std::optional<GooString> &userPassword = {}, void *guiDataA = nullptr, const std::function<void()> &xrefReconstructedCallback = {});
      |                     ~~~~~~~~~~~~^~~~
In file included from src/pdf/XPDFRenderer.h:51,
                 from src/pdf/XPDFRenderer.cpp:30:
/usr/include/poppler/PDFDoc.h:132:14: note: candidate: ‘PDFDoc::PDFDoc(std::unique_ptr<GooString>&&, const std::optional<GooString>&, const std::optional<GooString>&, void*, const std::function<void()>&)’
  132 |     explicit PDFDoc(std::unique_ptr<GooString> &&fileNameA, const std::optional<GooString> &ownerPassword = {}, const std::optional<GooString> &userPassword = {}, void *guiDataA = nullptr,
      |              ^~~~~~
/usr/include/poppler/PDFDoc.h:132:50: note:   no known conversion for argument 1 from ‘GooString*’ to ‘std::unique_ptr<GooString>&&’
  132 |     explicit PDFDoc(std::unique_ptr<GooString> &&fileNameA, const std::optional<GooString> &ownerPassword = {}, const std::optional<GooString> &userPassword = {}, void *guiDataA = nullptr,
      |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~
```
inkscape had a similar issue a few days ago that looks related: https://gitlab.com/inkscape/inbox/-/issues/6563

I have poppler 22.03.0-1 (upgraded 6 mar 2022).

### PR DESCRIPTION
**Pull request by letsfindaway**
Fix similar to the change done in inkscape, as referenced in #571. Also added flag to use c++17 compliance for compiling src/pdf as needed by poppler >= 22.01.

Closes #571, #560

### CODE REVIEW

**Comment by fsiegert** [comment]
Thanks for this! (And just for reference: I am using this fix also in the [Archlinux packaging](https://aur.archlinux.org/packages/openboard) now.)
