### ISSUE TITLE
[Building/Packaging] ‘class Ui::preferencesDialog’ has no member named ‘screenLayoutPreview’

### ISSUE THREAD

**Issue by Vekhir** [OpenBoard-org/OpenBoard#1406]
**Describe the problem**
During building, the following error occurs:
```
/build/openboard-git/src/OpenBoard/src/core/UBPreferencesController.cpp: In member function ‘void UBPreferencesController::adjustScreensPreferences()’:
/build/openboard-git/src/OpenBoard/src/core/UBPreferencesController.cpp:198:25: error: ‘class Ui::preferencesDialog’ has no member named ‘screenLayoutPreview’
  198 |     if (mPreferencesUI->screenLayoutPreview)
      |                         ^~~~~~~~~~~~~~~~~~~
/build/openboard-git/src/OpenBoard/src/core/UBPreferencesController.cpp:200:25: error: ‘class Ui::preferencesDialog’ has no member named ‘screenLayoutPreview’
  200 |         mPreferencesUI->screenLayoutPreview->refreshScreens();
      |                         ^~~~~~~~~~~~~~~~~~~
```

This issue is introduced in commit 3d2d77c57b15046e3ec631f6ed3db9a80547d328. As far as I can tell, this member variable never existed. I have no idea what this is supposed to do.

**Versions**
Provide version information for all components and libraries.
- OpenBoard version: `dev`

**Comment by kaamui** [comment]
Hi @Vekhir, 

Sorry about that, I made a mistake during merging on the preferences.ui. It is fixed and now used in the first tab of the preferences dialog

**Comment by Vekhir** [comment]
Thanks, OpenBoard builds fine now on Arch.
