### ISSUE TITLE
Compile on Fedora (30)

### ISSUE THREAD

**Issue by Axel-G** [OpenBoard-org/OpenBoard#228]
Hello,
what is todo to compile on Fedora 30? I try this adjusted script but it ends with error:

```
#Packages 
dnf install git qt5 qt5-qtsvg-devel qt5-qtwebkit-devel qt5-qtxmlpatterns-devel qt5-qtscript-devel openssl-devel libpaper-devel motif-devel qt5-qtmultimedia-devel qt5-qttools-devel redhat-lsb-core

#Source from git
git clone https://github.com/OpenBoard-Org/OpenBoard.git
git clone https://github.com/OpenBoard-Org/OpenBoard-Importer.git
git clone https://github.com/OpenBoard-Org/OpenBoard-ThirdParty.git

#Build the Third-Party libraries
cd OpenBoard-ThirdParty/freetype
qmake-qt5 freetype.pro -spec linux-g++
make

cd ../quazip
qmake-qt5 quazip.pro -spec linux-g++
make

cd ../xpdf/xpdf-3.04
./configure --with-freetype2-library="../../freetype/lib/linux" --with-freetype2-includes="../../freetype/freetype-2.6.1/include"
cd ..
qmake-qt5 xpdf.pro -spec linux-g++
make

#Build the Open-Sankoré document importer (optional)
cd ../../OpenBoard-Importer
qmake-qt5 OpenBoardImporter.pro -spec linux-g++
make

#Build OpenBoard
cd ../OpenBoard
qmake-qt5 OpenBoard.pro -spec linux-g++-64
make
``` 

Error:
make[1]: *** Keine Regel vorhanden, um das Ziel „QtWebKit/QWebView“, 
  benötigt von „build/linux/release/ui/ui_trapFlash.h“, zu erstellen.  Schluss.
make[1]: Verzeichnis „/home/ag/openboard/OpenBoard“ wird verlassen
make: *** [Makefile:42: release] Fehler 2

**Comment by JBBgameich** [comment]
Please apply this patch: https://gitlab.com/JBBgameich/OpenBoard/commit/68905184831c7965da3cc9c6c74731aead9dad22 or consider using the dev branch of my temporary [repository](https://gitlab.com/JBBgameich/OpenBoard) which contains some additional fixes for cross-distribution compatibility that were not yet accepted upstream.

**Comment by Axel-G** [comment]
Thx Jonah for your help.

Now it stopped here:
```

usr/bin/ld: build/linux/release/objects/UBFFmpegVideoEncoder.o: undefined reference to symbol 'swr_get_out_samples@@LIBSWRESAMPLE_3'
/usr/bin/ld: /usr/lib64/libswresample.so.3: error adding symbols: DSO missing from command line
collect2: Fehler: ld gab 1 als Ende-Status zurück
make[1]: *** [Makefile.Release:1386: openboard] Fehler 1
make[1]: Verzeichnis „/home/dev/Dokumente/CODING/OpenBoard/OpenBoard“ wird verlassen
make: *** [Makefile:42: release] Fehler 2

```

**Comment by JBBgameich** [comment]
Is this with the patch applied or my repository?
I'm currently trying to compile OpenBoard in a fedora docker container, and I'll post the resulting solution here if I find one.

**Comment by Axel-G** [comment]
i used your repo, the dev branch.

**Comment by Axel-G** [comment]
```
#!/bin/sh
#Install OpenBoard on Fedora (tested with Fedora 30)
#Hope all necassary packages are included in dnf install ;)

#Packages 
dnf install git qt5 qt5-qtsvg-devel qt5-qtwebkit-devel qt5-qtxmlpatterns-devel qt5-qtscript-devel openssl-devel libpaper-devel motif-devel qt5-qtmultimedia-devel qt5-qttools-devel redhat-lsb-core poppler-qt5-devel ffmpeg-devel

#quazip-devel installed, but error-message:
#Project MESSAGE: quazip not found on the system, falling back to ThirdParty

#link libs
ln -s qt5 /usr/include/poppler/cpp

#Source from git
git clone --branch dev https://gitlab.com/JBBgameich/OpenBoard.git
git clone https://github.com/OpenBoard-Org/OpenBoard-Importer.git
git clone https://github.com/OpenBoard-Org/OpenBoard-ThirdParty.git

#Build the Third-Party libraries
cd OpenBoard-ThirdParty/freetype
qmake-qt5 freetype.pro -spec linux-g++
make

cd ../quazip
qmake-qt5 quazip.pro -spec linux-g++
make

cd ../xpdf/xpdf-3.04
./configure --with-freetype2-library="../../freetype/lib/linux" --with-freetype2-includes="../../freetype/freetype-2.6.1/include"
cd ..
qmake-qt5 xpdf.pro -spec linux-g++
make

#Build the Open-Sankoré document importer (optional)
cd ../../OpenBoard-Importer
qmake-qt5 OpenBoardImporter.pro -spec linux-g++
make

#Build OpenBoard
cd ../OpenBoard
qmake-qt5 OpenBoard.pro -spec linux-g++-64
make

```

**Comment by JBBgameich** [comment]
Some parts need to be changed a little to use fedora packages for everything. It should be possible to build openboard completely without compiling any third parts library.

This is what kind of works for me, but it hasn't finished compiling yet.
```
#!/usr/bin/env bash
dnf install \
    https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm -y

dnf install \
    git \
    qt5 \
    qt5-qtsvg-devel \
    qt5-qtwebkit-devel \
    qt5-qtxmlpatterns-devel \
    qt5-qtscript-devel \
    openssl-devel \
    libpaper-devel \
    motif-devel \
    qt5-qtmultimedia-devel \
    qt5-qttools-devel \
    redhat-lsb-core \
    poppler-devel \
    quazip-qt5-devel \
    ffmpeg-devel \
    qt5-qttools-static \
    poppler-cpp-devel \
    -y

```

**Comment by JBBgameich** [comment]
Okay, everything is fixed now.
Please  use `git fetch && git reset origin/dev --hard` to reset your checkout to the latest state, and run `./ci_scripts/build.sh`
`ci_scripts/build.sh`
(In your case a simple make is probably enough since you did most of the work manually already)

**Comment by Axel-G** [comment]
thx for guiding Sir!
the compiling finished without error. Only i have in directory "build/linux/release" no product/OpenBoard file ... how to start ?

Sorry for my maybe stupid questions.

**Comment by Axel-G** [comment]
![Screenshot_20190509_225917](https://user-images.githubusercontent.com/40705043/57486568-8a333b00-72ae-11e9-9cd8-eb038dde6dc2.png)

**Comment by Axel-G** [comment]
Dear Jonah,
thank you very much !!!!
You made my day :)

**Comment by JBBgameich** [comment]
Btw, it looks like openboard can't find its resource data. Did you run make install already?

**Comment by Axel-G** [comment]
yes i do.
if  i start from the build directory it seems, data are available, start from installed version not.

**Comment by JBBgameich** [comment]
Is the data in `/usr/share/OpenBoard`?

**Comment by Axel-G** [comment]
ls -la /usr/share/OpenBoard/
insgesamt 0
drwxr-xr-x. 1 root root   20  9. Mai 23:16 .
drwxr-xr-x. 1 root root 6690  9. Mai 23:16 ..
drwxr-xr-x. 1 root root  332  9. Mai 23:16 etc
drwxr-xr-x. 1 root root  136  9. Mai 23:16 library

and in /usr/bin the binary

**Comment by pfps** [comment]
I got OpenBoard to compile and link under Fedora 31, but it isn't easy, even with the above information, which I only found after I had done the work.  It would be nice to have these instructions available in the installation document.
A problem that I ran into was openssl.  I had to downgrade to compat-openssl10-devel and then upgrade back.   (Isn't using openssl 1.0 a security risk?)

**Comment by JBBgameich** [comment]
OpenBoard doesn't required 1.0 anymore. Which branch did you use?

**Comment by JBBgameich** [comment]
CI passes for Fedora 31 (https://gitlab.com/JBBgameich/OpenBoard/-/jobs/477627595).
Please use the `dev` branch of https://gitlab.com/JBBgameich/OpenBoard.
You can use the scripts used by the ci to install dependencies and build openboard.
`./ci_scripts/fedora-install-deps.sh`
`./ci_scripts/build.sh`

The build script uses ccache to speed up later builds, if you don't need that, you can also just use `qmake-qt5 && make`.

The guide above is very outdated by now, there are no more manual steps and compiling of dependencies required.

**Comment by pfps** [comment]
@JBBgameich I cloned this repository this week.

When I compile without compat-openssl10-devel I get
```
In file included from src/core/UBApplication.cpp:66:
src/frameworks/UBCryptoUtils.h:63:24: error: field ‘mAesEncryptContext’ has incomplete type ‘EVP_CIPHER_CTX’ {aka ‘evp_cipher_ctx_st’}
   63 |         EVP_CIPHER_CTX mAesEncryptContext;
      |                        ^~~~~~~~~~~~~~~~~~
In file included from /usr/include/openssl/evp.h:14,
                 from src/frameworks/UBCryptoUtils.h:34,
                 from src/core/UBApplication.cpp:66:
/usr/include/openssl/ossl_typ.h:90:16: note: forward declaration of ‘EVP_CIPHER_CTX’ {aka ‘struct evp_cipher_ctx_st’}
   90 | typedef struct evp_cipher_ctx_st EVP_CIPHER_CTX;
      |                ^~~~~~~~~~~~~~~~~
In file included from src/core/UBApplication.cpp:66:
src/frameworks/UBCryptoUtils.h:64:24: error: field ‘mAesDecryptContext’ has incomplete type ‘EVP_CIPHER_CTX’ {aka ‘evp_cipher_ctx_st’}
   64 |         EVP_CIPHER_CTX mAesDecryptContext;
      |                        ^~~~~~~~~~~~~~~~~~
In file included from /usr/include/openssl/evp.h:14,
                 from src/frameworks/UBCryptoUtils.h:34,
                 from src/core/UBApplication.cpp:66:
/usr/include/openssl/ossl_typ.h:90:16: note: forward declaration of ‘EVP_CIPHER_CTX’ {aka ‘struct evp_cipher_ctx_st’}
   90 | typedef struct evp_cipher_ctx_st EVP_CIPHER_CTX;
      |                ^~~~~~~~~~~~~~~~~
make[1]: *** [Makefile.Release:3716: build/linux/release/objects/UBApplication.o] Error 1
make[1]: Leaving directory '/home/local/SoftwareDownloads/OpenBoard'
make: *** [Makefile:42: release] Error 2
```
To get to this point I had to find the Fedora versions of quite a few system packages.

**Comment by JBBgameich** [comment]
This repository (the GitHub one) only really works on Ubuntu 16.04 currently.
That's why for now you need to use the dev branch of my staging repository https://gitlab.com/JBBgameich/OpenBoard, which contains patches for building and installing on other linux distributions, such as Fedora.

A lot of work is happening on the dev-qt5.1x branch of this (the GitHub) repository, so maybe the extra patches will not be necessary anymore in the future.

**Comment by pfps** [comment]
Your dev branch works fine.  Are there plans to set up an RPM for Fedora or merge this branch back into the main repository?
I would not have persevered to this point if OpenBoard was not being used by my company.

**Comment by JBBgameich** [comment]
It's slowly being upstreamed into the main repository, but some of those patches break the existing release workflow of the team (such as supporting installation to /usr etc.).

**Comment by JBBgameich** [comment]
The snap store doesn't seem to have proper review of the submissions. The snap build was uploaded by a third-party and is just completely empty.

**Comment by pfps** [comment]
From https://openboard.ch/index.en.html
```
OpenBoard
Interactive whiteboard for schools and universities
For Windows, macOS and Linux.
```
Only working under Ubuntu doesn't satisfy this most-prominent description.
I'm pretty sure that my company is using OpenBoard because they believe that it can be relatively easily installed on any Linux system, not just Ubuntu.
Given that remote collaboration tools like OpenBoard are likely to get quite a bit more use now, it is probably a good time to spend a little effort to reduce the incorrect information on the web about OpenBoard installation.

**Comment by pfps** [comment]
Hmm, running the scripts in your dev branch completes without any errors, but I can't find any OpenBoard executable that it made.

**Comment by JBBgameich** [comment]
An executable named openboard should be created in the root of the OpenBoard repository. If there really is none, please send me the build logs so I can have look.

**Comment by pfps** [comment]
It's there.  I was looking for OpenBoard, which is the executable that the main branch makes.
Thanks.

**Comment by JBBgameich** [comment]
You can also use make install to install it into the system (with desktop entry etc) btw.

**Comment by pfps** [comment]
That's useful, thanks.
Now, about that full-screen-only malfeature ....  :-(

**Comment by JBBgameich** [comment]
What do you plan to use OpenBoard for if not as a fullscreen whiteboard?

**Comment by pfps** [comment]
I use it as a collaboration tool.  It is useful to have multiple windows open - OpenBoard for drawing and other windows for other things, like prepared slides or even video.

**Comment by tkalfaoglu** [comment]
It currently crashes with:
src/pdf/XPDFRenderer.cpp: In constructor ‘XPDFRenderer::XPDFRenderer(const QString&, bool)’:
src/pdf/XPDFRenderer.cpp:59:74: error: no matching function for call to ‘PDFDoc::PDFDoc(GooString*, int, int, int)’
   59 |     mDocument = new PDFDoc(new GooString(filename.toLocal8Bit()), 0, 0, 0); // the filename GString is deleted on PDFDoc desctruction

**Comment by letsfindaway** [comment]
see #571, #573. This problem should be fixed on current master.

BTW: What version are you compiling? I have never seen this code on line 59 of that file.
